/*
 * ultrasonic.c
 *
 *  Created on: Oct 15, 2022
 *      Author: HP
 */

#include"ultrasonic.h"
#include<util/delay.h>
#include"m_icu.h"
#include"m_gpio.h"

static uint16 g_time = 0;


/*
 * Description: function responsible for initialization of ultrasonic
 * 1-initialize ICU
 * 2-Setup the ICU call back function.
 * 3-Setup the direction for the trigger pin as output pin through the GPIO driver
 */
void Ultrasonic_init(void)
{
	Icu_configuration config = {CLK_8,RISING_EDGE};
	Icu_init(&config);
	GPIO_setupPinDirection( PORTB_ID,  PIN5_ID, PIN_OUTPUT);
	Icu_CallBackFunction (Ultrasonic_edgeProcessing);
}


/*
 * Description : function responsible for Send the Trigger pulse to the ultrasonic
 */
void Ultrasonic_Trigger(void)
{
	GPIO_writePin(PORTB_ID,  PIN5_ID, LOGIC_HIGH);
	_delay_us(10);
	GPIO_writePin(PORTB_ID,  PIN5_ID, LOGIC_LOW);
}


/*
 * Function description: function responsible for reading distance using ultrasonic
 *  1- send the trigger pulse by using Ultrasonic_Trigger function.so ultrasonic start to produce echo pulse
 *	2- Start the measurements by the ICU from this moment.
 *
 *	Return: The measured distance in Centimeter
 */
uint16 Ultrasonic_readDistance(void)
{
	Ultrasonic_Trigger();
    return (0.017 * g_time);
}


/*
 * Function description:
 * This is the call back function called by the ICU driver,
 * we initialize the call back in Ultrasonic_init()
 * the function used to calculate the high time (pulse time) generated by the ultrasonic sensor
 * */
void Ultrasonic_edgeProcessing(void)
{
	static uint8 g_count = 0;
	g_count++;
	if( g_count == 1)
	{
	Icu_ClearTime();
	Icu_EdgeDetectionType(FALLING_EDGE);
	}
	else if(g_count == 2)
	{
		g_time = Icu_getInputCaptureValue();
		Icu_EdgeDetectionType(RISING_EDGE);
		g_count=0;
	}

}

